chore: add demo application for easier testing
Maxl94/ngx-multi-sort-table pull request #178
Opened 2024-02-20 11:06 UTC by Catscratch

2024-02-22 14:55 UTC, Maxl94 requested changes

2024-02-22 14:55 UTC, Maxl94 commented on projects/demo/src/app/app.component.scss
> +  // th {
Maybe remove the commended line?

2024-02-22 14:55 UTC, Maxl94 commented on projects/demo/src/app/app.component.ts
> +    this.table.displayedColumns = ['id', 'name'] // intentionally left out 'progress' to show the bug
What about the bug?

2024-03-01 08:19 UTC, Catscratch commented on projects/demo/src/app/app.component.scss
> +  // th {
7e2968db

2024-03-01 09:03 UTC, merged